---
name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: "Lint Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super Linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_CSS: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYLINT: false # TODO: eh maybe later
          # VALIDATE_HTML: false # until / unless we figure out how to get htmlhint happy with our BC widget templates
          # VALIDATE_TERRAFORM_TERRASCAN: false
          # TODO: toggle GITHUB_ACTIONS back on after one, or both, of these issues are resolved:
          # https://github.com/github/super-linter/issues/1852
          # https://github.com/rhysd/actionlint/issues/91
          # VALIDATE_GITHUB_ACTIONS: false
          # JSCPD - meebee later...
          # VALIDATE_JSCPD_ALL_CODEBASE: true
